---
title: "R Notebook"
output: html_notebook
---

#output: rticles::rjournal_article

## Real Rata and Simulations

### Boston Housing data

```{r}
#source the functions. Will be changed to load package
source("../R/SINDEXQ_fun.R")

#load data from MASS
library(MASS)
#help(Boston)
medv<- Boston$medv
RM <- Boston$rm
logTAX <- log(Boston$tax)
PTRATIO <- Boston$ptratio
logLSTAT <- log(Boston$lstat)

X <- cbind(RM,logTAX,PTRATIO,logLSTAT)
y0<-medv - mean(medv)

#result is not the same with Wu 2010 as initial was not normalized in Wu 2010
#tianhai
#beta0 <- c(1,-1,0,-1);
beta0 <- NULL
tau_vec <- c(0.2,0.5,0.8)
est.coefficient <- matrix(NA, nrow = length(tau_vec), ncol = 5)
est.coefficient[,1] <- tau_vec
for (i in 1:length(tau_vec)){
  est <- siqr(y0,X,beta.inital = beta0, tau=tau_vec[i],maxiter = 20,tol = 1e-6)
  est.coefficient[i,2:5] <- est$beta
}
colnames(est.coefficient) <- c("quantile tau",colnames(X))
est.coefficient

```


```{r}
est <- siqr(y0,X,beta.inital = NULL, tau=0.2)
plot.si(est,bootstrap_interval = TRUE)
```

```{r}
est <- siqr(y0,X,beta.inital = NULL, tau=0.5)
plot.si(est,bootstrap_interval = TRUE)
```
```{r}
est <- siqr(y0,X,beta.inital = NULL, tau=0.8)
plot.si(est,bootstrap_interval = TRUE)
```

### Simulation

```{r eval = FALSE}
n <- 400
beta0 <- c(1, 2)/sqrt(5)
n_sim <- 100
tau_vec <- c(0.2,0.5,0.8)

data <- generate_data(n, true.theta=beta0, setting = "setting3",ncopy = n_sim)

sim_results <- array(NA,dim = c(length(tau_vec),length(beta0),n_sim))
for(m in 1:n_sim){
  X <- data$X
  Y <- data$Y[[m]]
  est.coefficient.sim <- matrix(NA, nrow = length(tau_vec), ncol = NCOL(X))
  for (i in 1:length(tau_vec)){
    est <- siqr(Y, X, beta.inital = NULL, tau=tau_vec[i],maxiter = 30,tol = 1e-8)
    est.coefficient.sim[i,] <- est$beta
  }
  sim_results[,,m] <- est.coefficient.sim
}
est.mean <- cbind(tau_vec,apply(sim_results,c(1,2),mean))
colnames(est.mean) <- c("tau","X1","X2")
est.mean
```


```{r}
est.se <- cbind(tau_vec,apply(sim_results,c(1,2),sd))
colnames(est.se) <- c("tau","X1","X2")
est.se
```

```{r figures-side, fig.show="hold", out.width="33%"}
par(mar = c(4, 4, .1, .1))
boxplot(data.frame(t(sim_results[1,,])), outline=T,notch=T,range=1,main = "Boxplots of Coefficient Estimates",horizontal = F)
boxplot(data.frame(t(sim_results[2,,])), outline=T,notch=T,range=1,main = "Boxplots of Coefficient Estimates",horizontal = F)
boxplot(data.frame(t(sim_results[3,,])), outline=T,notch=T,range=1,main = "Boxplots of Coefficient Estimates",horizontal = F)
```


```{r}
est <- siqr(Y,X,beta.inital = NULL, tau=0.5)
plot.si(est,bootstrap_interval = TRUE)
```

```{r}
Sys.sleep(100)
```

\bibliography{RJreferences}
